# Generated by Django 4.1.7 on 2023-04-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTiendita_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
