# Generated by Django 4.1.7 on 2023-04-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaTiendita_App', '0002_productos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
